/* Copyright 2005,2006 Sven Reimers, Florian Vogler
 *
 * This file is part of the Software Quality Environment Project.
 *
 * The Software Quality Environment Project is free software:
 * you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation,
 * either version 2 of the License, or (at your option) any later version.
 *
 * The Software Quality Environment Project is distributed in the hope that
 * it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.nbheaven.sqe.core.controlcenter.ui.panels;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import org.nbheaven.sqe.core.api.SQEManager;
import org.netbeans.api.project.Project;
import org.netbeans.api.project.ProjectUtils;

/**
 *
 * @author  sven
 */
public class ProjectStatistics extends javax.swing.JPanel implements PropertyChangeListener {
    
    private Project activeProject;
    
    /** Creates new form ProjectStatistics */
    public ProjectStatistics() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        noSourceFilesLabel = new javax.swing.JLabel();
        classpathLabel = new javax.swing.JLabel();
        classPathScrollPane = new javax.swing.JScrollPane();
        classPathList = new javax.swing.JList();
        name = new javax.swing.JLabel();
        sourceFiles = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.window);

        nameLabel.setText(org.openide.util.NbBundle.getMessage(ProjectStatistics.class, "ProjectStatistics.nameLabel.text")); // NOI18N

        noSourceFilesLabel.setText(org.openide.util.NbBundle.getMessage(ProjectStatistics.class, "ProjectStatistics.noSourceFilesLabel.text")); // NOI18N

        classpathLabel.setText(org.openide.util.NbBundle.getMessage(ProjectStatistics.class, "ProjectStatistics.classpathLabel.text")); // NOI18N

        classPathList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        classPathScrollPane.setViewportView(classPathList);

        name.setText(org.openide.util.NbBundle.getMessage(ProjectStatistics.class, "ProjectStatistics.name.text")); // NOI18N

        sourceFiles.setText(org.openide.util.NbBundle.getMessage(ProjectStatistics.class, "ProjectStatistics.sourceFiles.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(classpathLabel)
                    .add(nameLabel)
                    .add(noSourceFilesLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(name, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(90, 90, 90))
                    .add(layout.createSequentialGroup()
                        .add(sourceFiles, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(90, 90, 90))
                    .add(classPathScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameLabel)
                    .add(name))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(noSourceFilesLabel)
                    .add(sourceFiles))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(classpathLabel)
                    .add(classPathScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void propertyChange(PropertyChangeEvent evt) {
        activeProject = (Project) evt.getNewValue();
        updateData();
    }

    private void updateData() {
        if (null != activeProject) {
            name.setText(ProjectUtils.getInformation(activeProject).getDisplayName());        
        }
        else {
            name.setText("<No project selected>");
        }
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
        activeProject = SQEManager.getDefault().getActiveProject();
        SQEManager.getDefault().addPropertyChangeListener(SQEManager.PROP_ACTIVE_PROJECT, this);
        updateData();
    }

    @Override
    public void removeNotify() {
        SQEManager.getDefault().removePropertyChangeListener(SQEManager.PROP_ACTIVE_PROJECT, this);
        super.removeNotify();
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList classPathList;
    private javax.swing.JScrollPane classPathScrollPane;
    private javax.swing.JLabel classpathLabel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel noSourceFilesLabel;
    private javax.swing.JLabel sourceFiles;
    // End of variables declaration//GEN-END:variables
    
}
